"""INTEGRAÇÃO SANKHYA E GARNET

Revision ID: 1d62fb000aa0
Revises: eec7dd0d1dbb
Create Date: 2024-08-11 20:40:13.068366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d62fb000aa0'
down_revision = 'eec7dd0d1dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('integra_skn', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('integra_gar', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('integra_gar')
        batch_op.drop_column('integra_skn')

    # ### end Alembic commands ###
