"""CAMPO DOLLAR NEGOCIADO NA TRAVA

Revision ID: 2770c347c653
Revises: fbdebb195019
Create Date: 2024-09-03 23:58:15.670791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2770c347c653'
down_revision = 'fbdebb195019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autovenda', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('autovenda_empresa_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('autovenda_urs', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('autovenda_pwd', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('autovenda_pwd')
        batch_op.drop_column('autovenda_urs')
        batch_op.drop_column('autovenda_empresa_id')
        batch_op.drop_column('autovenda')

    # ### end Alembic commands ###
