"""CAMPO DOLLAR NEGOCIADO NA TRAVA

Revision ID: 5eebb5a2dce7
Revises: 1d62fb000aa0
Create Date: 2024-08-12 00:45:24.845707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eebb5a2dce7'
down_revision = '1d62fb000aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trava', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dollar', sa.Numeric(precision=10, scale=3), nullable=False))
        batch_op.add_column(sa.Column('removido', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trava', schema=None) as batch_op:
        batch_op.drop_column('removido')
        batch_op.drop_column('dollar')

    # ### end Alembic commands ###
