"""INTEGRAÇÃO COM SANKHYA

Revision ID: eec7dd0d1dbb
Revises: f32fb0c3146f
Create Date: 2024-07-31 00:55:22.082509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eec7dd0d1dbb'
down_revision = 'f32fb0c3146f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trava', schema=None) as batch_op:
        batch_op.add_column(sa.Column('integrado', sa.String(length=3), nullable=False))
        batch_op.alter_column('desagio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trava', schema=None) as batch_op:
        batch_op.alter_column('desagio',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('integrado')

    # ### end Alembic commands ###
